#
# Makefile for gmake (It should run with Microsoft's nmake)
# $Id$
#
############################################################################
.SUFFIXES: .exe .so .dll .a .lib .o .obj .cpp .cc .c .asm .s .y .pch .h .l

.c.obj:
	$(CC) $(CFLAGS) $(IFLAGS) $(Cpost) $<
.cpp.obj:
	$(CXX) $(CXXFLAGS) $(IFLAGS) $(CXXpost) $<
.cc.obj:
	$(CXX) $(CXXFLAGS) $(IFLAGS) $(CXXpost) $<

############################################################################
CC = cl -nologo -W3
CXX = $(CC)

Cpost = -c -Tc
CXXpost = -c -Tp

CFLAGS = -MD -Ox -G6 -vms $(DFLAGS) $(INCDIRS)
#CFLAGS = -MD -Od -Zi -G6 -vms $(DFLAGS) $(INCDIRS)

CXXFLAGS=$(CFLAGS) -GX

IFLAGS	= -Yuttinc.h

O = obj
A = lib
SO = dll
EXE = .exe
AOUT = -Fe

############################################################################
DFLAGS = -DHAVE_LIBZ -DHAVE_LIBSDL_MIXER
INCDIRS = -I. -I./glib/ -I./gdk/

LIBS =	win32/GetArgs.obj win32/getopt.obj win32/wsaerror.obj \
	win32/wsainit.obj win32/csmash.res \
	SDL.lib SDL_mixer.lib opengl32.lib glu32.lib zlib.lib \
	libjpeg.lib ws2_32.lib gtk/gtk-1.3.lib glib/glib-1.3.lib

SRCS = \
	Ball.cpp BallView.cpp BaseView.cpp Event.cpp HitMark.cpp \
	Howto.cpp HowtoView.cpp LoadImage.cpp PenAttack.cpp \
	PenDrive.cpp Player.cpp PlayerSelect.cpp PlayerSelectView.cpp \
	ShakeCut.cpp Sound.cpp Title.cpp TitleView.cpp PlayerView.cpp \
	View.cpp comPenAttack.cpp comPenDrive.cpp comPlayer.cpp \
	comShakeCut.cpp ComTrainingPenAttack.cpp TrainingPenAttack.cpp \
	MultiPlay.cpp TrainingPenDrive.cpp ComTrainingPenDrive.cpp \
	TrainingSelect.cpp TrainingSelectView.cpp TrainingView.cpp \
	FieldView.cpp SoloPlay.cpp PlayGame.cpp Control.cpp Training.cpp \
	Opening.cpp OpeningView.cpp MenuItem.cpp MenuItemView.cpp \
	main.cpp z.cpp parts.cpp xerror.cpp Launcher.cpp LobbyClient.cpp

OBJS = $(SRCS:.cpp=.obj)

TARGET = csmash$(EXE)

############################################################################
all: $(TARGET)
clean:
	rm -f $(TARGET) *.$(O) *.pch
	cd win32; $(MAKE) -f Makefile.nt CFLAGS="$(CFLAGS)" clean
distclean:
	rm -f $(TARGET) *.$(O) *~ *.bak depend.nt
	cd win32; $(MAKE) -f Makefile.nt CFLAGS="$(CFLAGS)" distclean

depend:
	touch depend.nt
	makedepend -fdepend.nt $(INCDIRS) -D_WIN32 -DHAVE_LIBZ -DHAVE_LIBSDL_MIXER $(SRCS)
	cat depend.nt | sed -e "s/.:\/.*\/VC98[^ ]*include\/[^ ]*//g" \
	| grep -v ".*:[ ]*$$" > depend.new
	mv depend.new depend.nt

$(TARGET): $(OBJS) win32/all
	$(CC) $(CFLAGS) $(AOUT)$@ $(OBJS) $(LIBS)

$(OBJS) : ttinc.pch

ttinc.pch: ttinc.h ttinc.cpp
	$(CXX) $(CXXFLAGS) $(IFLAGS) -Ycttinc.h $(CXXpost) ttinc.cpp

win32/all:
	cd win32 && $(MAKE) -f Makefile.nt CFLAGS="$(CFLAGS)" all

#-include depend.nt
############################################################################
# END
############################################################################
